# <div align="center" style="color:#EBF4F6; font-family:'Segoe UI', sans-serif;">Lab 2</div>
# <div align="center" style="color:#EBF4F6; font-family:'Segoe UI', sans-serif;">Bonus</div>

 * **Ahmed M. Y. Farani** | `1320236338`

In [ ]:
# Install the Pyterrier framework
!pip install python-terrier

Collecting python-terrier
  Downloading python_terrier-1.0-py3-none-any.whl.metadata (987 bytes)
Collecting pyterrier>=1.0 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyterrier-1.0.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.0.2)
Requirement already satisfied: pandas<3.0 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.2.2)
Requirement already satisfied: more_itertools in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (10.8.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.32.4)
Collecting ir_datasets>=0.3.2 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Collecting deprecated (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.16.3)
Collecting ir_measures>=0.4.1 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_measures-0.4.3-py3-none-any.whl.metadata (7.0 kB)
Collecting pytrec_eval_terrier>=0.5.3 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading pytrec_eval_terrier-0.5.10-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.1.6)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.14.6)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.3.8)
Collecting lz4 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.13.5)
Collecting pyjnius>=1.4.2 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyjnius-1.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting inscriptis>=2.2.0 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading inscriptis-2.7.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.3)
Collecting trec-car-tools>=2.5.4 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting warc3-wet>=0.2.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting zlib-state>=0.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading zlib_state-0.1.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (18.1.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.4.22)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.0.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (26.1)
Collecting lxml>=4.5.2 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading lxml-6.0.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.17.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Downloading python_terrier-1.0-py3-none-any.whl (1.4 kB)
Downloading pyterrier-1.0.4-py3-none-any.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.8/208.8 kB 10.7 MB/s eta 0:00:00
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 31.3 MB/s eta 0:00:00
Downloading ir_measures-0.4.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 2.9 MB/s eta 0:00:00
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 45.3 MB/s eta 0:00:00
Downloading pyjnius-1.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 44.0 MB/s eta 0:00:00
Downloading pytrec_eval_terrier-0.5.10-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (304 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 14.0 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 6.3 MB/s eta 0:00:00
Downloading inscriptis-2.7.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 2.1 MB/s eta 0:00:00
Downloading lxml-6.0.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 86.1 MB/s eta 0:00:00
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Building wheels for collected packages: warc3-wet-clueweb09, cbor
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18919 sha256=9c4cdfbd619c2af82b16c17a7a3a1dbad041f1b6632b03820c0831f209b05450
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55024 sha256=e7039de2425ac2d37a9d70289afb1a4bb92697459ffdb7cc6c4183fe82698fe4
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, pyjnius, cbor, zlib-state, unlzw3, trec-car-tools, lz4, lxml, ijson, deprecated, pytrec_eval_terrier, inscriptis, ir_measures, ir_datasets, pyterrier, python-terrier
  Attempting uninstall: lxml
    Found existing installation: lxml 6.1.0
    Uninstalling lxml-6.1.0:
      Successfully uninstalled lxml-6.1.0
Successfully installed cbor-1.0.0 deprecated-1.3.1 ijson-3.5.0 inscriptis-2.7.1 ir_datasets-0.5.11 ir_measures-0.4.3 lxml-6.0.4 lz4-4.4.5 pyjnius-1.7.0 pyterrier-1.0.4 python-terrier-1.0 pytrec_eval_terrier-0.5.10 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.12

In [ ]:
import pyterrier as pt
if not pt.started():
  pt.init()

/tmp/ipykernel_2305/1742394333.py:2: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():

terrier-assemblies 5.11 jar-with-dependencies not found, downloading to /root/.pyterrier...

https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/5.11/terrier-assemblies-5.11-jar-with-dependenci…

Done
terrier-python-helper 0.0.8 jar not found, downloading to /root/.pyterrier...

https://repo1.maven.org/maven2/org/terrier/terrier-python-helper/0.0.8/terrier-python-helper-0.0.8.jar:   0%| …

Done

Java started and loaded: pyterrier.java.colab, pyterrier.java, pyterrier.java.24, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_2305/1742394333.py:3: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [ ]:
# Install the Arabic stop words library
!pip install Arabic-Stopwords

Collecting Arabic-Stopwords
  Downloading Arabic_Stopwords-0.4.3-py3-none-any.whl.metadata (8.9 kB)
Collecting pyarabic>=0.6.2 (from Arabic-Stopwords)
  Downloading PyArabic-0.6.15-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from pyarabic>=0.6.2->Arabic-Stopwords) (1.17.0)
Downloading Arabic_Stopwords-0.4.3-py3-none-any.whl (360 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.5/360.5 kB 8.2 MB/s eta 0:00:00
Downloading PyArabic-0.6.15-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 kB 3.8 MB/s eta 0:00:00
Installing collected packages: pyarabic, Arabic-Stopwords
Successfully installed Arabic-Stopwords-0.4.3 pyarabic-0.6.15

In [ ]:
# We need to import the following libraries.
import pandas as pd
# To display the full text on the notebook without truncation
pd.set_option('display.max_colwidth', 150)
import re
from snowballstemmer import stemmer
import arabicstopwords.arabicstopwords as stp
# Make your loops show a smart progress meter
from tqdm import tqdm

### **Exercise**
Index an Arabic collection of your choice. You can use the Arabic dataset available at **[Huggingface](https://huggingface.co/datasets/arbml/ArabicDEv2/viewer/default/validation)**

In [ ]:
from datasets import load_dataset

dataset = load_dataset("arbml/ArabicDEv2", split='validation')

df = dataset.to_pandas()
df['docno'] = df.index.astype(str)
df = df.rename(columns={'query': 'raw_text'})
df

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

dataset_infos.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

data/validation-00000-of-00001-b4e4245a8(…):   0%|          | 0.00/7.07k [00:00<?, ?B/s]

Generating validation split:   0%|          | 0/139 [00:00<?, ? examples/s]

,id,raw_text,docno
0,QALD2_te-59,ولايات أمريكية في نفس منطقة ولاية يوتا الزمنية,0
1,QALD2_tr-8,ولايات ألمانيا يحكمها الحزب الاشتراكي الديمقراطي,1
2,SemSearch_LS-21,والدا ليلي ألين,2
3,QALD2_te-90,مقر إقامة رئيس وزراء إسبانيا,3
4,QALD2_te-11,سائق سباق الفورمولا 1 مع اكبر عدد من السباقات,4
...,...,...,...
134,SemSearch_LS-20,أشقاء قوبلاي خان,134
135,QALD2_te-41,أسس \ أسست إنتل,135
136,SemSearch_LS-14,آلهة سكنت على جبل أوليمبوس,136
137,INEX_LD-2012347,مقعد فلوريدا مقاطعة داد,137
138,INEX_XER-113,سائقو الفورمولا 1 الذين فازوا بجائزة موناكو الكبرى,138

1.   **Remove stopwords.**

In [ ]:
# Removing Stop Words function
def remove_stopWords(sentence):
    terms=[]
    stopWords= set(stp.stopwords_list())
    for term in sentence.split() :
        if term not in stopWords :
           terms.append(term)
    return " ".join(terms)

df["text"]=df["raw_text"].apply(remove_stopWords)
print("==> Removing Stopwords.")
df[['docno','raw_text','text']]

==> Removing Stopwords.

,docno,raw_text,text
0,0,ولايات أمريكية في نفس منطقة ولاية يوتا الزمنية,ولايات أمريكية منطقة ولاية يوتا الزمنية
1,1,ولايات ألمانيا يحكمها الحزب الاشتراكي الديمقراطي,ولايات ألمانيا يحكمها الحزب الاشتراكي الديمقراطي
2,2,والدا ليلي ألين,والدا ألين
3,3,مقر إقامة رئيس وزراء إسبانيا,مقر إقامة رئيس وزراء إسبانيا
4,4,سائق سباق الفورمولا 1 مع اكبر عدد من السباقات,سائق سباق الفورمولا 1 اكبر عدد السباقات
...,...,...,...
134,134,أشقاء قوبلاي خان,أشقاء قوبلاي خان
135,135,أسس \ أسست إنتل,أسس \ أسست إنتل
136,136,آلهة سكنت على جبل أوليمبوس,آلهة سكنت جبل أوليمبوس
137,137,مقعد فلوريدا مقاطعة داد,مقعد فلوريدا مقاطعة داد
138,138,سائقو الفورمولا 1 الذين فازوا بجائزة موناكو الكبرى,سائقو الفورمولا 1 فازوا بجائزة موناكو الكبرى

2.   **Normalization.**

In [ ]:
# A function to normalize the tweets
def normalize(text):
    text = re.sub("[إأٱآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "ء", text)
    text = re.sub("ئ", "ء", text)
    text = re.sub("ة", "ه", text)
    return(text)

df["text"]=df["text"].apply(normalize)
print("==> Normalizing.")
df[['docno','raw_text','text']]

==> Normalizing.

,docno,raw_text,text
0,0,ولايات أمريكية في نفس منطقة ولاية يوتا الزمنية,ولايات امريكيه منطقه ولايه يوتا الزمنيه
1,1,ولايات ألمانيا يحكمها الحزب الاشتراكي الديمقراطي,ولايات المانيا يحكمها الحزب الاشتراكي الديمقراطي
2,2,والدا ليلي ألين,والدا الين
3,3,مقر إقامة رئيس وزراء إسبانيا,مقر اقامه رءيس وزراء اسبانيا
4,4,سائق سباق الفورمولا 1 مع اكبر عدد من السباقات,ساءق سباق الفورمولا 1 اكبر عدد السباقات
...,...,...,...
134,134,أشقاء قوبلاي خان,اشقاء قوبلاي خان
135,135,أسس \ أسست إنتل,اسس \ اسست انتل
136,136,آلهة سكنت على جبل أوليمبوس,الهه سكنت جبل اوليمبوس
137,137,مقعد فلوريدا مقاطعة داد,مقعد فلوريدا مقاطعه داد
138,138,سائقو الفورمولا 1 الذين فازوا بجائزة موناكو الكبرى,ساءقو الفورمولا 1 فازوا بجاءزه موناكو الكبري

3.   **Stemming.**

In [ ]:
# Specify that we want to stem arabic text
ar_stemmer = stemmer("arabic")
# Define the stemming function
def stem(sentence):
    return " ".join([ar_stemmer.stemWord(i) for i in sentence.split()])

df['text']=df['text'].apply(stem)
print("==> Stemming.")
df[['docno','raw_text','text']]

==> Stemming.

,docno,raw_text,text
0,0,ولايات أمريكية في نفس منطقة ولاية يوتا الزمنية,لايا امريك منطق ولا يوتا زمنيه
1,1,ولايات ألمانيا يحكمها الحزب الاشتراكي الديمقراطي,لايا مانيا يحكم حزب اشتراك ديمقراط
2,2,والدا ليلي ألين,والد الين
3,3,مقر إقامة رئيس وزراء إسبانيا,مقر اقام رءيس زراء اسباني
4,4,سائق سباق الفورمولا 1 مع اكبر عدد من السباقات,ساءق سباق فورمولا 1 اكبر عدد سباق
...,...,...,...
134,134,أشقاء قوبلاي خان,اشقاء قوبلا خان
135,135,أسس \ أسست إنتل,اسس \ اسس انتل
136,136,آلهة سكنت على جبل أوليمبوس,الهه سكن جبل اوليمبوس
137,137,مقعد فلوريدا مقاطعة داد,مقعد لوريد مقاطع داد
138,138,سائقو الفورمولا 1 الذين فازوا بجائزة موناكو الكبرى,ساءق فورمولا 1 فاز جاءز موناك كبر

4.   **Data Cleaning.**

In [ ]:
# A function to clean the tweets
def clean(text):
   text = re.sub(r"@[\w]*", " ", text)
   text = re.sub(r"[\.\,\#_\|\:\?\?\/\=\\]", " ", text)
   text = re.sub(r'\t', ' ', text)
   text = re.sub(r'\n', ' ', text)
   text = re.sub(r"\s+", " ", text)
   return text

# We will clean each tweet in the collection
df["text"]=df["text"].apply(clean)
print("==> After Cleaning")
df[['docno','raw_text','text']]

==> After Cleaning

,docno,raw_text,text
0,0,ولايات أمريكية في نفس منطقة ولاية يوتا الزمنية,لايا امريك منطق ولا يوتا زمنيه
1,1,ولايات ألمانيا يحكمها الحزب الاشتراكي الديمقراطي,لايا مانيا يحكم حزب اشتراك ديمقراط
2,2,والدا ليلي ألين,والد الين
3,3,مقر إقامة رئيس وزراء إسبانيا,مقر اقام رءيس زراء اسباني
4,4,سائق سباق الفورمولا 1 مع اكبر عدد من السباقات,ساءق سباق فورمولا 1 اكبر عدد سباق
...,...,...,...
134,134,أشقاء قوبلاي خان,اشقاء قوبلا خان
135,135,أسس \ أسست إنتل,اسس اسس انتل
136,136,آلهة سكنت على جبل أوليمبوس,الهه سكن جبل اوليمبوس
137,137,مقعد فلوريدا مقاطعة داد,مقعد لوريد مقاطع داد
138,138,سائقو الفورمولا 1 الذين فازوا بجائزة موناكو الكبرى,ساءق فورمولا 1 فاز جاءز موناك كبر

3.   **Indexing.**

In [ ]:
indexer = pt.DFIndexer("./bonusIndex", overwrite=True)
indexer.setProperty("tokeniser", "UTFTokeniser")
index_ref = indexer.index(df["text"], df["docno"])
index_ref.toString()

/tmp/ipykernel_2305/754819617.py:1: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer("./bonusIndex", overwrite=True)

10:02:33.147 [main] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (0) - further warnings are suppressed
10:02:35.159 [main] WARN org.terrier.structures.indexing.Indexer -- Indexed 124 empty documents

'./bonusIndex/data.properties'

In [ ]:
# We will first load the index
index = pt.IndexFactory.of(index_ref)
# We will call getCollectionStatistics() to check the stats
print(index.getCollectionStatistics().toString())

Number of documents: 139
Number of terms: 12
Number of postings: 15
Number of fields: 0
Number of tokens: 15
Field names: []
Positions:   false

In [ ]:
for kv in index.getLexicon():
  print("%s -> %s " % (kv.getKey(), kv.getValue().toString()))

1 -> term0 Nt=4 TF=4 maxTF=1 @{0 0 0}
11 -> term7 Nt=1 TF=1 maxTF=1 @{0 5 0}
13 -> term11 Nt=1 TF=1 maxTF=1 @{0 6 6}
14 -> term4 Nt=1 TF=1 maxTF=1 @{0 8 4}
1945 -> term8 Nt=1 TF=1 maxTF=1 @{0 10 2}
1950 -> term2 Nt=1 TF=1 maxTF=1 @{0 12 0}
1960 -> term5 Nt=1 TF=1 maxTF=1 @{0 13 0}
1974 -> term6 Nt=1 TF=1 maxTF=1 @{0 14 6}
51 -> term3 Nt=1 TF=1 maxTF=1 @{0 16 4}
747 -> term10 Nt=1 TF=1 maxTF=1 @{0 18 0}
hs850 -> term1 Nt=1 TF=1 maxTF=1 @{0 19 6}
mn -> term9 Nt=1 TF=1 maxTF=1 @{0 20 6}